#!/bin/bash

#Change these variables to meet your setup

#The user we're copying files to.
USER=swanson
#The ip of the server.
SERVER=192.168.1.109
#The target directory of the file/files.
DIR=/home/swanson/vanilla1.3/plugins

if [ -z $1 ]
    then
    echo 'Usage: scopy <file> {directory}'
    exit 1;
elif [ -z $2 ]
    then
    scp $1 $USER@$SERVER:$DIR
else
    scp $1 $USER@$SERVER:$2
fi
